### PR TITLE
Merge Upstream into Master

### PR DESCRIPTION
**Pull request by djmetzle**
### Merge Upstream
It appears that there has been some extensive development on the upstream.
Changes include:
- Help output changes (many of them)
- Tagging support, which we may be able to use
- Percona Specific feautes such as `LOCK BINLOG FOR BACKUP`

### CODE REVIEW

**Comment by djmetzle** [comment]
@danielbeardsley How do we proceed here? I trust the upstream devs. Looking through the diff, there's nothing that looks severely different. Just a lot of very useful feature adds.

**Comment by danielbeardsley** [comment]
Perhaps test it on the slave first?

**Comment by djmetzle** [comment]
Error Output:
`Unknown option: mysql-stop-slave`

**Comment by danielbeardsley** [comment]
Superseded by #9 which does the reverse merge first to deal with the conflicts.

**Pull request closed without merging**
